### ISSUE TITLE
Requête décret

### ISSUE THREAD

**Issue by PatGendre** [afimb/gtfslib-python#1]
cf. ce texte http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000031589954&dateTexte=&categorieLien=id 
"tout service régulier de transport public de personnes routier urbain
présente un espacement moyen des arrêts inférieur ou égal à 500 mètres et un
ratio entre la fréquence en heure de pointe et la fréquence en heure creuse
inférieur ou égal à 2,5"
- il faut donc savoir calculer l'espacement moyen des arrêts (défini à l'article 2)
- et calculer le ratio de fréquence HP/HC (défini à l'article 3)
- puis écrire une fonction qui calcule si une ligne est urbaine ou interurbaine (ou pour toute les lignes d'un feed)

**Comment by laurentg** [comment]
Implémenté dans le plugin "Decret_2015_1610".
