### ISSUE TITLE
Two frequencies can refer to the same trip?

### ISSUE THREAD

**Issue by skinkie** [afimb/gtfslib-python#41]
https://github.com/afimb/gtfslib-python/blob/master/gtfslib/converter.py#L623

Can you give an example of the above. Is it legal to do define a trip with a stop pattern and instantiate it multiple times in frequencies?

**Comment by laurentg** [comment]
This exemple here has three frequencies referring to the same trip: https://developers.google.com/transit/gtfs/examples/gtfs-feed#frequenciestxt

It's legal and even documented (for example you can't have overlapping ranges, but the end-time of a range can be perfectly identical to the start range of the next).

I think this would be rather common to do so, if you have the same pattern with varying frequency during the day.
