### ISSUE TITLE
Crashes while exporting when departure or arrival time is 00:00

### ISSUE THREAD

**Issue by Josef-A** [afimb/gtfslib-python#48]
Hi,

When I use the export plugin to save the loaded database GTFS I get an error for stop times where the arrival or departure time is 0.

I uses postgres. 

I get the following stack trace:
Traceback (most recent call last):
  File "R:/Skript/gtfs_routines/gtfs_lib_run.py", line 15, in <module>
    gtfsplugins.gtfsrun.main()
  File "R:\Skript\gtfslib-python\gtfsplugins\gtfsrun.py", line 101, in main
    retval = plugin.run(context, **kwargs)
  File "R:\Skript\gtfslib-python\gtfsplugins\export.py", line 84, in run
    fmttime(stoptime.departure_time if stoptime.departure_time else stoptime.arrival_time),
  File "R:\Skript\gtfslib-python\gtfslib\utils.py", line 38, in fmttime
    h = ssm / 3600
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Process finished with exit code 1

I think that's the problem is in line 83 and 84 in export.py.
There is an if statement to handle if stoptime.arrival is None. But it will also trigger in the rare cases where the time is 0.

My workaround is to change the lines from:
fmttime(stoptime.arrival_time if stoptime.arrival_time else stoptime.departure_time),
fmttime(stoptime.departure_time if stoptime.departure_time else stoptime.arrival_time),

to:
fmttime(stoptime.arrival_time if stoptime.arrival_time is not None else stoptime.departure_time),
fmttime(stoptime.departure_time if stoptime.departure_time is not None else stoptime.arrival_time),

That worked for my gtfs feed.

I haven't used Github that much so I do not know how to do a proper "Pull request". 

Thanks for a good framework.

Regards
          Josef Andersson

**Comment by laurentg** [comment]
Indeed the line `if stoptime.arrival_time` will be evaluated to false by python for a 0 time. I'll do the correction asap, many thanks for the report!
