### ISSUE TITLE
Rework GTFS export plugin filtering

### ISSUE THREAD

**Issue by laurentg** [afimb/gtfslib-python#51]
See #50 for more information.

**Comment by laurentg** [comment]
The support for filtering in the GTFS export plugin has never been fully tested and is currently buggy. The problem with filtering each object is that the semantics are not always the same between a GTFS export and the common sense. For example filtering stops on Route or Agency will list all stops from all stop_times; but this is not enough for a GTFS export as one need the parent station too. Joining on the parent station for the DAO would be brain-dead though.

The proper solution is to only use the provided filter for basic classes of object (agencies, routes, trips, stop times, stops, calendar, calendar_dates) and deriving the proper filter for the other objects based on the previous returned object lists (stop > parent stations, stops+stations > transfers, zones+routes > fares_attributes > fare_rules, etc...)

**Comment by Josef-A** [comment]
I do not have any fares in my feed. So I can't test that. An minor remark. If the output file is optional and empty. Would it be better to not save it at all?

**Comment by laurentg** [comment]
Good remark. I'll create an issue for that.
