### ISSUE TITLE
Remove optional empty files from GTFS export

### ISSUE THREAD

**Issue by laurentg** [afimb/gtfslib-python#53]
`transfers.txt`, `fare_rules.txt` and `fare_attributes.txt`.

**Comment by Josef-A** [comment]
I got an error from this.
The new code is within the with PrettyCsv( ... clausal.
Therefore the file is still in use when its try to remove it.

I just changed the indentation. Then it worked.

shapes.txt is also optional

**Comment by laurentg** [comment]
Ha OK that should depend on the python version / OS, I did not had the issue here (python 3.4.2 on Debian Linux). Correcting.
