### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by gac55** [afimb/gtfslib-python#54]
I'm trying to install using Python 2.7

On step 3, I get `You must give at least one requirement to install (see "pip help install")`

Is there supposed to be a `requirements.txt` file?

Thanks!

```
$ git clone git@github.com:afimb/gtfslib-python.git
$ cd gtfslib-python
$ pip install
$ gtfsdbloader --help

**Comment by laurentg** [comment]
@gac55 The README is incorrect, it should read `pip install .`
