### ISSUE TITLE
direction_id is not added to the db for trips

### ISSUE THREAD

**Issue by elad661** [afimb/gtfslib-python#57]
see https://developers.google.com/transit/gtfs/reference/trips-file

direction_id is an optional field, but it is present on some feeds.

**Comment by laurentg** [comment]
Are you sure about this? `direction_id` is present on the ORM and is loaded, I just tested on one of my feed.

**Comment by elad661** [comment]
You're right, it is added to the db.
however, it's not present in `model.py`, so you can't use it for queries like you can use other fields.

**Comment by laurentg** [comment]
No, you can filter on the field, even though it's not initialized in the model. It's the case for some optional fields. I've added a small unit-test to test it (https://github.com/afimb/gtfslib-python/commit/90d290b810e3537aefe3fd8962a17df72c41b981).

**Comment by elad661** [comment]
Oh, I see. Thanks.
