### ISSUE TITLE
don't call clear_mappers() in orm.py

### ISSUE THREAD

**Issue by elad661** [afimb/gtfslib-python#59]
I'm not sure why you call ``clear_mappers()`` there:
https://github.com/afimb/gtfslib-python/blob/master/gtfslib/orm.py#L35-L36

But since my project needs to use both gtfslib and a database of my own (which has mappings that do not fit in gtfslib-python), that call to ``clear_mappers()`` breaks my code, since it clears my mappers too, and not only mappers defined by gtfslib-python.

**Comment by laurentg** [comment]
AFAIR it was only for making the unit-test work. But it's probably better indeed to make the `_Orm` class a singleton, and remove this call. As the comment is saying, this is hackish :)

**Comment by laurentg** [comment]
Making the `_Orm` class a singleton is rather complicated, as it accept arguments at construction. the better solution is probably to clear the mappers in the unit-tests only, using a setup method.

**Comment by elad661** [comment]
Thanks!
