### ISSUE TITLE
Add a tag

### ISSUE THREAD

**Issue by mhugo** [afimb/gtfslib-python#65]
Hi,
Could gtfslib be tagged with a version ?
So that it can be packaged and made available on pypi.
https://gitlab.com/Oslandia/tempus_loader is ready to use gtfslib for its GTFS import part, but it lacks a correct dependency declaration for setup.py

**Comment by laurentg** [comment]
Tag v1.0.0 created. First official version.

**Comment by laurentg** [comment]
@mhugo Is that sufficient for a release on PyPI? I'm not really familiar with the process.

**Comment by mhugo** [comment]
The version of the package should be changed appropriately [here](https://github.com/afimb/gtfslib-python/blob/master/gtfslib/__init__.py)

I'm not completely familiar with pypi neither. I think you can either manually send a zip or use setup.py and twine to upload it

**Comment by laurentg** [comment]
Right, thanks. Should be OK now.

**Comment by mhugo** [comment]
Thanks ! FYI I've uploaded it on pypi here : https://pypi.python.org/pypi?:action=display&name=gtfslib&version=1.0.0

**Comment by laurentg** [comment]
@mhugo Great, thanks!
